#!/bin/sh -ex

## speeqe
SRC=/usr/local/src
PATCHES=$SRC/speeqe-patches
WEBROOT=/var/www/django/speeqeweb
SCRIPTS=$WEBROOT/webroot/scripts

# install punjab (speeqe dep)
cd $SRC/punjab
python setup.py install

# configure and patch speeqeweb
mkdir -p $(dirname $WEBROOT)
mv $SRC/speeqe/speeqeweb $WEBROOT
chown -R root:root $WEBROOT

mkdir -p /etc/speeqe
mv $PATCHES/settings.py /etc/speeqe/settings.py
mv $PATCHES/local_settings.js /etc/speeqe/local_settings.js
mv $PATCHES/botbg.jpg $WEBROOT/webroot/images/default_theme/botbg.jpg

ln -fs /etc/speeqe/settings.py $WEBROOT/settings.py
ln -s /etc/speeqe/local_settings.js $WEBROOT/webroot/scripts/local_settings.js

patch $WEBROOT/templates/index.html $PATCHES/index.html.diff
patch $WEBROOT/webroot/client.html $PATCHES/client.html.diff

JQUERY=$(basename $SCRIPTS/jquery-*.min.js)
ln -s $JQUERY $SCRIPTS/$(echo $JQUERY | sed "s|min.||")

ln -s /usr/share/pyshared/django/contrib/admin/media/ $WEBROOT/webroot/admin_media

mkdir -p /var/lib/sqlite
$WEBROOT/manage.py syncdb --noinput
chown -R www-data:www-data /var/lib/sqlite

mkdir -p /var/log/speeqe
chown www-data:www-data /var/log/speeqe

## ejabberd
XMPP_DOMAIN=example.com
ADMIN_PASS=turnkey

echo "ERLANG_NODE=ejabberd@localhost" >> /etc/default/ejabberd
/usr/lib/inithooks/bin/ejabberd.sh $XMPP_DOMAIN $ADMIN_PASS

# apache configuration
echo Listen 12322 >> /etc/apache2/ports.conf
a2dissite default
a2ensite speeqeweb
a2ensite ejabberd

a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

# cleanup
rm -rf $SRC/*

