#!/bin/bash -e
# regenerate ejabberd / speeqe secrets

CONF=/etc/speeqe/settings.py
sed -i "s/^SECRET_KEY = \(.*\)/SECRET_KEY = \'$(mcookie)$(mcookie)\'/" $CONF

# copy over certificate (Debian #368414)
cp /etc/ssl/certs/cert.pem /etc/ejabberd/ejabberd.pem
